# Generated by Django 2.1.3 on 2018-11-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_administrador_usuario_operador'),
        ('cartera', '0003_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_Abonar', models.IntegerField(verbose_name='Total a abonar')),
                ('total_pegar', models.IntegerField()),
                ('Fecha_abono', models.DateField(auto_now_add=True, verbose_name='Fecha de abono')),
                ('abono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartera.creditos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['Fecha_abono'],
            },
        ),
    ]
