# Generated by Django 2.1.3 on 2018-11-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_abonos'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloqueo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField(verbose_name='identificacion')),
            ],
        ),
    ]
